apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: myrazorbankapp
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: myrazorbankapp
spec:
  source:
    git:
      url: https://github.com/PradeepLoganathan/MyBankRazor.git
      ref:
        branch: main